/* * Program: Smart Alarm Clock - main Module
 * Name: Yuanchen Zhang
 * Date: 2026-01-07
 */

/* Main Thread entry function */
#include "main_thread.h"
#include "bsp_api.h"
#include "gx_api.h"
#include "gui/guiapp_specifications.h"
#include "gui/guiapp_resources.h"


#if defined(BSP_BOARD_S7G2_SK)
#include "hardware/lcd.h"
#endif

/***********************************************************************************************************************
    Private function prototypes
 ***********************************************************************************************************************/

void main_thread_entry(void);

#if defined(BSP_BOARD_S7G2_SK)
void g_lcd_spi_callback(spi_callback_args_t * p_args);
#endif

/***********************************************************************************************************************
    Private global variables
 ***********************************************************************************************************************/


GX_WINDOW_ROOT * p_window_root;
extern GX_CONST GX_STUDIO_WIDGET *guiapp_widget_table[];

/*******************************************************************************************************************//**
    @brief  Primary logic for handling events generated by the various sub-systems.
 ***********************************************************************************************************************/
void main_thread_entry(void) {
    ssp_err_t        err;

    UINT      status = TX_SUCCESS;

    /* Initializes GUIX. */
    status = gx_system_initialize();
    if(TX_SUCCESS != status)
    {
        while(1);
    }

    /* Initializes GUIX drivers. */
    err = g_sf_el_gx.p_api->open (g_sf_el_gx.p_ctrl, g_sf_el_gx.p_cfg);
    if(SSP_SUCCESS != err)
    {
        while(1);
    }

    gx_studio_display_configure ( DISPLAY_1,
                                  g_sf_el_gx.p_api->setup,
                                  LANGUAGE_ENGLISH,
                                  DISPLAY_1_THEME_1,
                                  &p_window_root );

    err = g_sf_el_gx.p_api->canvasInit(g_sf_el_gx.p_ctrl, p_window_root);
    if(SSP_SUCCESS != err)
    {
        while(1);
    }

    // Create the widgets we have defined with the GUIX data structures and resources.
    GX_CONST GX_STUDIO_WIDGET ** pp_studio_widget = &guiapp_widget_table[0];
    GX_WIDGET * p_first_screen = NULL;

    while (GX_NULL != *pp_studio_widget)
    {
        // We must first create the widgets according the data generated in GUIX Studio.

        // Once we are working on the widget we want to see first, save the pointer for later.
        if (0 == strcmp("window_screen", (char*)(*pp_studio_widget)->widget_name))
        {
            gx_studio_named_widget_create((*pp_studio_widget)->widget_name, (GX_WIDGET *)p_window_root, GX_NULL);
        } else {
            gx_studio_named_widget_create((*pp_studio_widget)->widget_name, GX_NULL, GX_NULL);
        }
        // Move to next top-level widget
        pp_studio_widget++;
    }
    // Attach the first screen to the root so we can see it when the root is shown
   gx_widget_attach(p_window_root, p_first_screen);


    if(TX_SUCCESS != status)
    {
            while(1);
    }

    /* Shows the root window to make it and patients screen visible. */
    status = gx_widget_show(p_window_root);
    if(TX_SUCCESS != status)
    {
        while(1);
    }

    /* Lets GUIX run. */
    status = gx_system_start();
    if(TX_SUCCESS != status)
    {
        while(1);
    }

#if defined(BSP_BOARD_S7G2_SK)
    /** Open the SPI driver to initialize the LCD (SK-S7G2) **/
    err = g_spi_lcdc.p_api->open(g_spi_lcdc.p_ctrl, (spi_cfg_t *)g_spi_lcdc.p_cfg);//open lcd
    if (err)
    {
        while(1);
    }
    /** Setup the ILI9341V (SK-S7G2) **/
    ILI9341V_Init();
    g_external_irq10.p_api->open(g_external_irq10.p_ctrl, g_external_irq10.p_cfg);//open two interrupts
    g_external_irq11.p_api->open(g_external_irq11.p_ctrl, g_external_irq11.p_cfg);
#endif


    while(1)
    {




        tx_thread_sleep (10);
    }
}



#if defined(BSP_BOARD_S7G2_SK)
void g_lcd_spi_callback(spi_callback_args_t * p_args)
{
    (void)p_args;
    tx_semaphore_ceiling_put(&g_main_semaphore_lcdc, 1);
}
#endif






void touch_panel_v2_callback(sf_touchpanel_v2_callback_args_t *p_args)
{
    GX_EVENT gxe;
    bool send_event = true;

    switch(p_args->payload.event_type)
    {
          case SF_TOUCH_PANEL_V2_EVENT_DOWN:
              gxe.gx_event_type = GX_EVENT_PEN_DOWN;
              break;
          case SF_TOUCH_PANEL_V2_EVENT_UP:
              gxe.gx_event_type = GX_EVENT_PEN_UP;
              break;
          case SF_TOUCH_PANEL_V2_EVENT_HOLD:
          case SF_TOUCH_PANEL_V2_EVENT_MOVE:
              gxe.gx_event_type = GX_EVENT_PEN_DRAG;
              break;
          case SF_TOUCH_PANEL_V2_EVENT_INVALID:
              send_event = false;
              break;
          default:
              break;

    }
    if (send_event)
        {

        gxe.gx_event_sender         = GX_ID_NONE;
        gxe.gx_event_target         = 0;  /* the event to be routed to the widget that has input focus */
        gxe.gx_event_display_handle = 0;

        gxe.gx_event_payload.gx_event_pointdata.gx_point_x = (GX_VALUE)(p_args->payload.x);
        gxe.gx_event_payload.gx_event_pointdata.gx_point_y = (GX_VALUE)(320 - p_args->payload.y);
        gx_system_event_send(&gxe);
        }


}

//SW5
void sw5_external_irq_cb(external_irq_callback_args_t *p_args)
{
    switch (p_args->channel)
       {
           case 10:

               tx_semaphore_ceiling_put(&g_sw5_semaphore, 1);//put semaphore
               break;

           default:
               break;
       }

}

//SW4
void sw4_external_irq_cb(external_irq_callback_args_t *p_args)
{
    switch (p_args->channel)
    {
        case 11:
            /* add your code here for channel 11 ISR*/
            tx_semaphore_ceiling_put(&g_sw4_semaphore, 1);//put semaphore
            break;

        default:
            break;
    }
}
